# Generated by Django 4.2.dev20220919031901 on 2022-11-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
