# Generated by Django 4.2.dev20220919031901 on 2022-11-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_channel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("message_data", models.CharField(max_length=200, null=True)),
                ("both_people", models.ManyToManyField(null=True, to="app.person")),
            ],
        ),
    ]
