# Generated by Django 4.2.dev20220919031901 on 2022-11-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_channel_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="user",
            new_name="sender",
        ),
    ]
