# Generated by Django 4.2.dev20220919031901 on 2022-11-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_user_channel_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="people",
            field=models.ManyToManyField(to="app.person"),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="both_people",
            field=models.ManyToManyField(to="app.person"),
        ),
    ]
