# Generated by Django 4.2.dev20220919031901 on 2022-12-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_directmessage_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
