# Generated by Django 4.2.dev20220919031901 on 2022-12-02 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0009_alter_directmessage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="both_people",
            field=models.ManyToManyField(blank=True, to="app.person"),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
