# Generated by Django 4.2.dev20220919031901 on 2022-12-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_directmessage_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="profile1.png", null=True, upload_to=""
            ),
        ),
    ]
