# Generated by Django 4.2.dev20220919031901 on 2022-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_person_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="static/images/Bojack.png", null=True, upload_to=""
            ),
        ),
    ]
